language: node_js
node_js:
 - node

script:
 - npm run lint  
after_success:
 - npm run deploy
deploy:
  skip_cleanup: true
  
  provider: firebase
  project: node-project-84f81
  token: $FIREBASE_TOKEN
notifications:
 email: false