language: node_js
node_js:
 - node
  before_install:
 - npm i -g firebase-tools
script:
 - npm run lint  
after_success:
 - npm run deploy
deploy:
  provider: firebase
  token: 1//0cwlRPDJRHe5dCgYIARAAGAwSNwF-L9IruM_Zt7MQodgEF10AnAk-UFJxuEtyzdzjq_ARMQAHpbqSkG6RvO-5WvJpz_KVOUnJNyQ
notifications:
 email: false